version: '3.8'

services:
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend/src/data:/app/data
  #   ports:
  #     - "3000:3000" # Mapea el puerto 3000 del host al puerto 80 del contenedor
  #   depends_on:
  #     - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000" # Mapea el puerto 8000 del host al puerto 8000 del contenedor
    volumes:
      - ./frontend/src/data:/app/data